description: platypus

environment:
  image: alsordon/pt2-mttl:latest
  setup:
  - pip install pydantic==1.10.9 --user
  env:
    WANDB_MODE: disabled
    DATASET_RESERVED_FREE_DISK_SPACE: 10000000000
    TRANSFORMERS_CACHE: /mnt/default/data/llama-2/
    NI_DATA_DIR: /mnt/default/data/sni/
    MMLU_DATA_DIR: /mnt/default/data/mmlu/data/

code:
  local_dir: $CONFIG_DIR/..


jobs:
- name: platypus-13b-lowlr
  sku: G1-A100
  process_count_per_node: -1
  command:
  - cd projects/instr_routing
  - CUDA_VISIBLE_DEVICES=0 python finetune_llama.py 
    -c configs/platypus/llama2_13b.json+configs/platypus/llama2_13b_dense.json
    -k output_dir=$$AMLT_OUTPUT_DIR
    hf_token_hub="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"
    eval_superni=True
    eval_mmlu=True
    learning_rate=0.00005

- name: platypus-13b-vsmear-no-lr
  sku: G1-A100
  process_count_per_node: -1
  command:
  - cd projects/instr_routing
  - CUDA_VISIBLE_DEVICES=0 python finetune_llama.py 
    -c configs/platypus/llama2_13b.json+configs/platypus/llama2_13b_vsmear.json
    -k output_dir=$$AMLT_OUTPUT_DIR
    hf_token_hub="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"
    eval_superni=True
    eval_mmlu=True
    model_modifier=vsmear

- name: platypus-13b-smear
  sku: G1-A100
  process_count_per_node: -1
  command:
  - cd projects/instr_routing
  - CUDA_VISIBLE_DEVICES=0 python finetune_llama.py 
    -c configs/platypus/llama2_13b.json+configs/platypus/llama2_13b_vsmear.json
    -k output_dir=$$AMLT_OUTPUT_DIR
    hf_token_hub="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"
    eval_superni=True
    eval_mmlu=True
    model_modifier=smear
    router_learning_rate=1e-3
